In [1]:
from google.colab import files

uploaded = files.upload()

Saving employee_promotion_dataset.csv to employee_promotion_dataset.csv

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("employee_promotion_dataset.csv")

In [4]:
df

,Age,Experience,Education,City,Department,WorkType,PerformanceScore,ProjectsCompleted,Overtime,Gender,Salary,Promoted
0,28,5,High School,Mumbai,HR,Government,70.0,2,No,Male,24376.0,No
1,35,14,NaN,Hyderabad,HR,Startup,54.0,7,No,Female,64412.0,No
2,31,8,Bachelor,Bangalore,HR,Government,NaN,2,No,Male,56763.0,No
3,59,38,Diploma,Pune,Sales,Private,69.0,12,Yes,Female,124850.0,No
4,25,3,High School,Bangalore,IT,Government,79.0,14,No,Male,45530.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...
245,29,4,Bachelor,Chennai,Finance,Government,72.0,15,Yes,Male,71046.0,No
246,37,16,Diploma,NaN,Marketing,Self-Employed,62.0,13,No,Female,68500.0,No
247,55,32,Bachelor,NaN,Finance,Private,61.0,6,Yes,Female,115403.0,No
248,25,1,Diploma,Pune,HR,Private,72.0,3,No,Male,30934.0,No
249,32,6,High School,Mumbai,Operations,Private,99.0,5,No,Female,46337.0,No

In [6]:
df.shape

(250, 12)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                250 non-null    int64
 1   Experience         250 non-null    int64
 2   Education          238 non-null    object
 3   City               238 non-null    object
 4   Department         238 non-null    object
 5   WorkType           250 non-null    object
 6   PerformanceScore   238 non-null    float64
 7   ProjectsCompleted  250 non-null    int64
 8   Overtime           250 non-null    object
 9   Gender             250 non-null    object
 10  Salary             238 non-null    float64
 11  Promoted           250 non-null    object
dtypes: float64(2), int64(3), object(7)
memory usage: 23.6+ KB

In [8]:
df.describe()

,Age,Experience,PerformanceScore,ProjectsCompleted,Salary
count,250.000000,250.000000,238.000000,250.000000,238.000000
mean,40.940000,17.392000,71.638655,7.776000,91557.050420
std,11.243579,11.115239,11.246551,4.673885,46604.399631
min,21.000000,0.000000,45.000000,0.000000,22397.000000
25%,31.000000,8.000000,63.250000,4.000000,69330.000000
50%,41.000000,18.000000,71.000000,8.000000,87216.000000
75%,51.000000,27.000000,79.000000,12.000000,107581.250000
max,60.000000,38.000000,100.000000,15.000000,438630.000000

In [9]:
df.isnull()

,Age,Experience,Education,City,Department,WorkType,PerformanceScore,ProjectsCompleted,Overtime,Gender,Salary,Promoted
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
245,False,False,False,False,False,False,False,False,False,False,False,False
246,False,False,False,True,False,False,False,False,False,False,False,False
247,False,False,False,True,False,False,False,False,False,False,False,False
248,False,False,False,False,False,False,False,False,False,False,False,False
249,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
df.isnull().sum()

Age                   0
Experience            0
Education            12
City                 12
Department           12
WorkType              0
PerformanceScore     12
ProjectsCompleted     0
Overtime              0
Gender                0
Salary               12
Promoted              0
dtype: int64

In [13]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
245    False
246    False
247    False
248    False
249    False
Length: 250, dtype: bool

In [14]:
df[df.duplicated()]

Empty DataFrame
Columns: [Age, Experience, Education, City, Department, WorkType, PerformanceScore, ProjectsCompleted, Overtime, Gender, Salary, Promoted]
Index: []

In [15]:
df

,Age,Experience,Education,City,Department,WorkType,PerformanceScore,ProjectsCompleted,Overtime,Gender,Salary,Promoted
0,28,5,High School,Mumbai,HR,Government,70.0,2,No,Male,24376.0,No
1,35,14,NaN,Hyderabad,HR,Startup,54.0,7,No,Female,64412.0,No
2,31,8,Bachelor,Bangalore,HR,Government,NaN,2,No,Male,56763.0,No
3,59,38,Diploma,Pune,Sales,Private,69.0,12,Yes,Female,124850.0,No
4,25,3,High School,Bangalore,IT,Government,79.0,14,No,Male,45530.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...
245,29,4,Bachelor,Chennai,Finance,Government,72.0,15,Yes,Male,71046.0,No
246,37,16,Diploma,NaN,Marketing,Self-Employed,62.0,13,No,Female,68500.0,No
247,55,32,Bachelor,NaN,Finance,Private,61.0,6,Yes,Female,115403.0,No
248,25,1,Diploma,Pune,HR,Private,72.0,3,No,Male,30934.0,No
249,32,6,High School,Mumbai,Operations,Private,99.0,5,No,Female,46337.0,No

In [22]:
df.select_dtypes(include=['object' , 'category']).columns

Index(['Education', 'City', 'Department', 'WorkType', 'Overtime', 'Gender',
       'Promoted'],
      dtype='object')

In [20]:
df['Education'].value_counts()

Education
Bachelor       74
Master         54
Diploma        48
High School    38
PhD            24
Name: count, dtype: int64

In [24]:
df['City'].value_counts()

City
Mumbai       43
Pune         43
Delhi        43
Bangalore    42
Chennai      36
Hyderabad    31
Name: count, dtype: int64

In [25]:
df['Department'].value_counts()

Department
Marketing     44
HR            43
Finance       43
IT            39
Operations    38
Sales         31
Name: count, dtype: int64

In [26]:
df['WorkType'].value_counts()

WorkType
Private          72
Government       63
Self-Employed    59
Startup          56
Name: count, dtype: int64

In [27]:
df['Overtime'].value_counts()

Overtime
No     125
Yes    125
Name: count, dtype: int64

In [28]:
df['Gender'].value_counts()

Gender
Female    134
Male      116
Name: count, dtype: int64

In [29]:
df['Promoted'].value_counts()

Promoted
No     226
Yes     24
Name: count, dtype: int64

In [30]:
categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    print("="*40)
    print(col)
    print(df[col].value_counts())
    print()

========================================
Education
Education
Bachelor       74
Master         54
Diploma        48
High School    38
PhD            24
Name: count, dtype: int64

========================================
City
City
Mumbai       43
Pune         43
Delhi        43
Bangalore    42
Chennai      36
Hyderabad    31
Name: count, dtype: int64

========================================
Department
Department
Marketing     44
HR            43
Finance       43
IT            39
Operations    38
Sales         31
Name: count, dtype: int64

========================================
WorkType
WorkType
Private          72
Government       63
Self-Employed    59
Startup          56
Name: count, dtype: int64

========================================
Overtime
Overtime
No     125
Yes    125
Name: count, dtype: int64

========================================
Gender
Gender
Female    134
Male      116
Name: count, dtype: int64

========================================
Promoted
Promoted
No     226
Yes     24
Name: count, dtype: int64

In [31]:
df

,Age,Experience,Education,City,Department,WorkType,PerformanceScore,ProjectsCompleted,Overtime,Gender,Salary,Promoted
0,28,5,High School,Mumbai,HR,Government,70.0,2,No,Male,24376.0,No
1,35,14,NaN,Hyderabad,HR,Startup,54.0,7,No,Female,64412.0,No
2,31,8,Bachelor,Bangalore,HR,Government,NaN,2,No,Male,56763.0,No
3,59,38,Diploma,Pune,Sales,Private,69.0,12,Yes,Female,124850.0,No
4,25,3,High School,Bangalore,IT,Government,79.0,14,No,Male,45530.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...
245,29,4,Bachelor,Chennai,Finance,Government,72.0,15,Yes,Male,71046.0,No
246,37,16,Diploma,NaN,Marketing,Self-Employed,62.0,13,No,Female,68500.0,No
247,55,32,Bachelor,NaN,Finance,Private,61.0,6,Yes,Female,115403.0,No
248,25,1,Diploma,Pune,HR,Private,72.0,3,No,Male,30934.0,No
249,32,6,High School,Mumbai,Operations,Private,99.0,5,No,Female,46337.0,No

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                250 non-null    int64
 1   Experience         250 non-null    int64
 2   Education          238 non-null    object
 3   City               238 non-null    object
 4   Department         238 non-null    object
 5   WorkType           250 non-null    object
 6   PerformanceScore   238 non-null    float64
 7   ProjectsCompleted  250 non-null    int64
 8   Overtime           250 non-null    object
 9   Gender             250 non-null    object
 10  Salary             238 non-null    float64
 11  Promoted           250 non-null    object
dtypes: float64(2), int64(3), object(7)
memory usage: 23.6+ KB

In [ ]:
numerical_features = ['Age' , 'Experience' , 'PerformanceScore' , 'ProjectsCompleted' , 'Salary']
ordinal_features = ['Education']
nominal_features = ['City' , 'Department' , 'WorkType' , 'Overtime' , 'Gender' , '']
target = 'Promoted'

In [34]:
X = df.drop('Promoted' , axis = 1)
y = df['Promoted']

In [36]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42 , stratify = y)

In [37]:
from sklearn.impute import SimpleImputer
median_imputer = SimpleImputer(strategy = 'median')

In [38]:
X_train[['Salary' , 'PerformanceScore']] = median_imputer.fit_transform(X_train[['Salary' , 'PerformanceScore']])

In [40]:
X_test[['Salary' , 'PerformanceScore']] = median_imputer.transform(X_test[['Salary' , 'PerformanceScore']])