In [5]:
from google.colab import files

uploaded = files.upload()

Saving employee_promotion_dataset.csv to employee_promotion_dataset.csv

In [69]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [70]:
df = pd.read_csv("employee_promotion_dataset.csv")

In [71]:
df

,Age,Experience,Education,City,Department,WorkType,PerformanceScore,ProjectsCompleted,Overtime,Gender,Salary,Promoted
0,28,5,High School,Mumbai,HR,Government,70.0,2,No,Male,24376.0,No
1,35,14,NaN,Hyderabad,HR,Startup,54.0,7,No,Female,64412.0,No
2,31,8,Bachelor,Bangalore,HR,Government,NaN,2,No,Male,56763.0,No
3,59,38,Diploma,Pune,Sales,Private,69.0,12,Yes,Female,124850.0,No
4,25,3,High School,Bangalore,IT,Government,79.0,14,No,Male,45530.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...
245,29,4,Bachelor,Chennai,Finance,Government,72.0,15,Yes,Male,71046.0,No
246,37,16,Diploma,NaN,Marketing,Self-Employed,62.0,13,No,Female,68500.0,No
247,55,32,Bachelor,NaN,Finance,Private,61.0,6,Yes,Female,115403.0,No
248,25,1,Diploma,Pune,HR,Private,72.0,3,No,Male,30934.0,No
249,32,6,High School,Mumbai,Operations,Private,99.0,5,No,Female,46337.0,No

In [72]:
df.shape

(250, 12)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                250 non-null    int64
 1   Experience         250 non-null    int64
 2   Education          238 non-null    object
 3   City               238 non-null    object
 4   Department         238 non-null    object
 5   WorkType           250 non-null    object
 6   PerformanceScore   238 non-null    float64
 7   ProjectsCompleted  250 non-null    int64
 8   Overtime           250 non-null    object
 9   Gender             250 non-null    object
 10  Salary             238 non-null    float64
 11  Promoted           250 non-null    object
dtypes: float64(2), int64(3), object(7)
memory usage: 23.6+ KB

In [74]:
df.describe()

,Age,Experience,PerformanceScore,ProjectsCompleted,Salary
count,250.000000,250.000000,238.000000,250.000000,238.000000
mean,40.940000,17.392000,71.638655,7.776000,91557.050420
std,11.243579,11.115239,11.246551,4.673885,46604.399631
min,21.000000,0.000000,45.000000,0.000000,22397.000000
25%,31.000000,8.000000,63.250000,4.000000,69330.000000
50%,41.000000,18.000000,71.000000,8.000000,87216.000000
75%,51.000000,27.000000,79.000000,12.000000,107581.250000
max,60.000000,38.000000,100.000000,15.000000,438630.000000

In [75]:
df.isnull()

,Age,Experience,Education,City,Department,WorkType,PerformanceScore,ProjectsCompleted,Overtime,Gender,Salary,Promoted
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
245,False,False,False,False,False,False,False,False,False,False,False,False
246,False,False,False,True,False,False,False,False,False,False,False,False
247,False,False,False,True,False,False,False,False,False,False,False,False
248,False,False,False,False,False,False,False,False,False,False,False,False
249,False,False,False,False,False,False,False,False,False,False,False,False

In [76]:
df.isnull().sum()

Age                   0
Experience            0
Education            12
City                 12
Department           12
WorkType              0
PerformanceScore     12
ProjectsCompleted     0
Overtime              0
Gender                0
Salary               12
Promoted              0
dtype: int64

In [77]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
245    False
246    False
247    False
248    False
249    False
Length: 250, dtype: bool

In [78]:
df[df.duplicated()]

Empty DataFrame
Columns: [Age, Experience, Education, City, Department, WorkType, PerformanceScore, ProjectsCompleted, Overtime, Gender, Salary, Promoted]
Index: []

In [79]:
df

,Age,Experience,Education,City,Department,WorkType,PerformanceScore,ProjectsCompleted,Overtime,Gender,Salary,Promoted
0,28,5,High School,Mumbai,HR,Government,70.0,2,No,Male,24376.0,No
1,35,14,NaN,Hyderabad,HR,Startup,54.0,7,No,Female,64412.0,No
2,31,8,Bachelor,Bangalore,HR,Government,NaN,2,No,Male,56763.0,No
3,59,38,Diploma,Pune,Sales,Private,69.0,12,Yes,Female,124850.0,No
4,25,3,High School,Bangalore,IT,Government,79.0,14,No,Male,45530.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...
245,29,4,Bachelor,Chennai,Finance,Government,72.0,15,Yes,Male,71046.0,No
246,37,16,Diploma,NaN,Marketing,Self-Employed,62.0,13,No,Female,68500.0,No
247,55,32,Bachelor,NaN,Finance,Private,61.0,6,Yes,Female,115403.0,No
248,25,1,Diploma,Pune,HR,Private,72.0,3,No,Male,30934.0,No
249,32,6,High School,Mumbai,Operations,Private,99.0,5,No,Female,46337.0,No

In [80]:
df.select_dtypes(include=['object' , 'category']).columns

Index(['Education', 'City', 'Department', 'WorkType', 'Overtime', 'Gender',
       'Promoted'],
      dtype='object')

In [81]:
df['Education'].value_counts()

Education
Bachelor       74
Master         54
Diploma        48
High School    38
PhD            24
Name: count, dtype: int64

In [82]:
df['City'].value_counts()

City
Mumbai       43
Pune         43
Delhi        43
Bangalore    42
Chennai      36
Hyderabad    31
Name: count, dtype: int64

In [83]:
df['Department'].value_counts()

Department
Marketing     44
HR            43
Finance       43
IT            39
Operations    38
Sales         31
Name: count, dtype: int64

In [84]:
df['WorkType'].value_counts()

WorkType
Private          72
Government       63
Self-Employed    59
Startup          56
Name: count, dtype: int64

In [85]:
df['Overtime'].value_counts()

Overtime
No     125
Yes    125
Name: count, dtype: int64

In [86]:
df['Gender'].value_counts()

Gender
Female    134
Male      116
Name: count, dtype: int64

In [87]:
df['Promoted'].value_counts()

Promoted
No     226
Yes     24
Name: count, dtype: int64

In [88]:
categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    print("="*40)
    print(col)
    print(df[col].value_counts())
    print()

========================================
Education
Education
Bachelor       74
Master         54
Diploma        48
High School    38
PhD            24
Name: count, dtype: int64

========================================
City
City
Mumbai       43
Pune         43
Delhi        43
Bangalore    42
Chennai      36
Hyderabad    31
Name: count, dtype: int64

========================================
Department
Department
Marketing     44
HR            43
Finance       43
IT            39
Operations    38
Sales         31
Name: count, dtype: int64

========================================
WorkType
WorkType
Private          72
Government       63
Self-Employed    59
Startup          56
Name: count, dtype: int64

========================================
Overtime
Overtime
No     125
Yes    125
Name: count, dtype: int64

========================================
Gender
Gender
Female    134
Male      116
Name: count, dtype: int64

========================================
Promoted
Promoted
No     226
Yes     24
Name: count, dtype: int64

In [89]:
df

,Age,Experience,Education,City,Department,WorkType,PerformanceScore,ProjectsCompleted,Overtime,Gender,Salary,Promoted
0,28,5,High School,Mumbai,HR,Government,70.0,2,No,Male,24376.0,No
1,35,14,NaN,Hyderabad,HR,Startup,54.0,7,No,Female,64412.0,No
2,31,8,Bachelor,Bangalore,HR,Government,NaN,2,No,Male,56763.0,No
3,59,38,Diploma,Pune,Sales,Private,69.0,12,Yes,Female,124850.0,No
4,25,3,High School,Bangalore,IT,Government,79.0,14,No,Male,45530.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...
245,29,4,Bachelor,Chennai,Finance,Government,72.0,15,Yes,Male,71046.0,No
246,37,16,Diploma,NaN,Marketing,Self-Employed,62.0,13,No,Female,68500.0,No
247,55,32,Bachelor,NaN,Finance,Private,61.0,6,Yes,Female,115403.0,No
248,25,1,Diploma,Pune,HR,Private,72.0,3,No,Male,30934.0,No
249,32,6,High School,Mumbai,Operations,Private,99.0,5,No,Female,46337.0,No

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                250 non-null    int64
 1   Experience         250 non-null    int64
 2   Education          238 non-null    object
 3   City               238 non-null    object
 4   Department         238 non-null    object
 5   WorkType           250 non-null    object
 6   PerformanceScore   238 non-null    float64
 7   ProjectsCompleted  250 non-null    int64
 8   Overtime           250 non-null    object
 9   Gender             250 non-null    object
 10  Salary             238 non-null    float64
 11  Promoted           250 non-null    object
dtypes: float64(2), int64(3), object(7)
memory usage: 23.6+ KB

In [91]:
numerical_features = ['Age' , 'Experience' , 'PerformanceScore' , 'ProjectsCompleted' , 'Salary']
ordinal_features = ['Education']
nominal_features = ['City' , 'Department' , 'WorkType' , 'Overtime' , 'Gender' , '']
target = 'Promoted'

In [92]:
X = df.drop('Promoted' , axis = 1)
y = df['Promoted']

In [93]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42 , stratify = y)

In [94]:
from sklearn.impute import SimpleImputer
median_imputer = SimpleImputer(strategy = 'median')

In [95]:
X_train[['Salary' , 'PerformanceScore']] = median_imputer.fit_transform(X_train[['Salary' , 'PerformanceScore']])

In [96]:
X_test[['Salary' , 'PerformanceScore']] = median_imputer.transform(X_test[['Salary' , 'PerformanceScore']])

In [97]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 39 to 181
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                200 non-null    int64
 1   Experience         200 non-null    int64
 2   Education          192 non-null    object
 3   City               190 non-null    object
 4   Department         189 non-null    object
 5   WorkType           200 non-null    object
 6   PerformanceScore   200 non-null    float64
 7   ProjectsCompleted  200 non-null    int64
 8   Overtime           200 non-null    object
 9   Gender             200 non-null    object
 10  Salary             200 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 18.8+ KB

In [98]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 177 to 234
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                50 non-null     int64
 1   Experience         50 non-null     int64
 2   Education          46 non-null     object
 3   City               48 non-null     object
 4   Department         49 non-null     object
 5   WorkType           50 non-null     object
 6   PerformanceScore   50 non-null     float64
 7   ProjectsCompleted  50 non-null     int64
 8   Overtime           50 non-null     object
 9   Gender             50 non-null     object
 10  Salary             50 non-null     float64
dtypes: float64(2), int64(3), object(6)
memory usage: 4.7+ KB

In [99]:
from sklearn.impute import SimpleImputer
mode_imputer = SimpleImputer(strategy = 'most_frequent')

In [100]:
X_train[['Education' , 'City' , 'Department']] = mode_imputer.fit_transform(X_train[['Education' , 'City' , 'Department']])
X_test[['Education' , 'City' , 'Department']] = mode_imputer.transform(X_test[['Education' , 'City' , 'Department']])

In [101]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 39 to 181
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                200 non-null    int64
 1   Experience         200 non-null    int64
 2   Education          200 non-null    object
 3   City               200 non-null    object
 4   Department         200 non-null    object
 5   WorkType           200 non-null    object
 6   PerformanceScore   200 non-null    float64
 7   ProjectsCompleted  200 non-null    int64
 8   Overtime           200 non-null    object
 9   Gender             200 non-null    object
 10  Salary             200 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 18.8+ KB

In [102]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 177 to 234
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                50 non-null     int64
 1   Experience         50 non-null     int64
 2   Education          50 non-null     object
 3   City               50 non-null     object
 4   Department         50 non-null     object
 5   WorkType           50 non-null     object
 6   PerformanceScore   50 non-null     float64
 7   ProjectsCompleted  50 non-null     int64
 8   Overtime           50 non-null     object
 9   Gender             50 non-null     object
 10  Salary             50 non-null     float64
dtypes: float64(2), int64(3), object(6)
memory usage: 4.7+ KB

In [103]:
X_train

,Age,Experience,Education,City,Department,WorkType,PerformanceScore,ProjectsCompleted,Overtime,Gender,Salary
39,45,23,Bachelor,Mumbai,Operations,Private,70.0,3,No,Male,84963.0
19,51,27,Diploma,Delhi,HR,Startup,71.0,0,No,Female,87199.0
219,50,25,Master,Chennai,Finance,Startup,79.0,3,No,Female,109050.0
93,28,4,PhD,Delhi,Operations,Government,70.0,0,Yes,Female,76781.0
67,32,6,Bachelor,Chennai,Finance,Government,70.0,13,No,Male,69201.0
...,...,...,...,...,...,...,...,...,...,...,...
63,56,35,High School,Chennai,Sales,Startup,69.0,9,Yes,Male,107240.0
214,34,11,Bachelor,Pune,IT,Startup,68.0,9,Yes,Female,65050.0
146,47,26,Master,Mumbai,Finance,Private,54.0,11,Yes,Male,114628.0
103,27,5,Bachelor,Mumbai,Operations,Startup,61.0,7,Yes,Female,62627.0
181,25,4,Bachelor,Delhi,Sales,Private,60.0,9,No,Male,49037.0

In [104]:
categorical_columns = X_train.select_dtypes(include = 'object').columns

In [105]:
categorical_columns

Index(['Education', 'City', 'Department', 'WorkType', 'Overtime', 'Gender'], dtype='object')

In [106]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(drop = 'first' ,handle_unknown = 'ignore' , sparse_output = False)

encoded_X_train = encoder.fit_transform(X_train[categorical_columns])
encoded_X_test = encoder.transform(X_test[categorical_columns])

In [107]:
encoded_X_train.shape

(200, 19)

In [108]:
encoded_X_test.shape

(50, 19)

In [109]:
encoder.categories_

[array(['Bachelor', 'Diploma', 'High School', 'Master', 'PhD'],
       dtype=object),
 array(['Bangalore', 'Chennai', 'Delhi', 'Hyderabad', 'Mumbai', 'Pune'],
       dtype=object),
 array(['Finance', 'HR', 'IT', 'Marketing', 'Operations', 'Sales'],
       dtype=object),
 array(['Government', 'Private', 'Self-Employed', 'Startup'], dtype=object),
 array(['No', 'Yes'], dtype=object),
 array(['Female', 'Male'], dtype=object)]

In [110]:
encoder.get_feature_names_out(categorical_columns)

array(['Education_Diploma', 'Education_High School', 'Education_Master',
       'Education_PhD', 'City_Chennai', 'City_Delhi', 'City_Hyderabad',
       'City_Mumbai', 'City_Pune', 'Department_HR', 'Department_IT',
       'Department_Marketing', 'Department_Operations',
       'Department_Sales', 'WorkType_Private', 'WorkType_Self-Employed',
       'WorkType_Startup', 'Overtime_Yes', 'Gender_Male'], dtype=object)

In [111]:
encoded_X_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 1., 1.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [112]:
encoded_X_test

array([[0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
        1., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 1.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
        1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
        0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
        0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        1., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 1., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
        0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
        0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
        0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 1., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
        0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 1., 1.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 1., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
        0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
        1., 1., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
        0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
        0., 0., 1.],
       [0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0.,
        0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
        0., 1., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
        0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
        1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1.,
        0., 1., 1.],
       [0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
        1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
        0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        1., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
        0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
        0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
        0., 1., 0.]])

In [115]:
encoded_X_train = pd.DataFrame(encoded_X_train , columns = encoder.get_feature_names_out(categorical_columns) ,index = X_train.index)
encoded_X_test = pd.DataFrame(encoded_X_test , columns = encoder.get_feature_names_out(categorical_columns), index = X_test.index)

In [116]:
encoded_X_train

,Education_Diploma,Education_High School,Education_Master,Education_PhD,City_Chennai,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune,Department_HR,Department_IT,Department_Marketing,Department_Operations,Department_Sales,WorkType_Private,WorkType_Self-Employed,WorkType_Startup,Overtime_Yes,Gender_Male
39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
19,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
219,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
93,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
67,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
214,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
146,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
103,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
181,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0

In [117]:
encoded_X_test

,Education_Diploma,Education_High School,Education_Master,Education_PhD,City_Chennai,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune,Department_HR,Department_IT,Department_Marketing,Department_Operations,Department_Sales,WorkType_Private,WorkType_Self-Employed,WorkType_Startup,Overtime_Yes,Gender_Male
177,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
211,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
246,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
166,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
193,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
233,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
188,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
56,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
210,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
167,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
218,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
207,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
50,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
100,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
206,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
95,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
14,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
223,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
21,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
249,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
54,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
228,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
78,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
143,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
74,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
238,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
38,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
117,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
198,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
60,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
110,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
77,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
133,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0
173,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
116,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
144,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
242,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
96,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
187,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
126,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
52,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
113,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
59,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
107,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
234,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [118]:
X_train

,Age,Experience,Education,City,Department,WorkType,PerformanceScore,ProjectsCompleted,Overtime,Gender,Salary
39,45,23,Bachelor,Mumbai,Operations,Private,70.0,3,No,Male,84963.0
19,51,27,Diploma,Delhi,HR,Startup,71.0,0,No,Female,87199.0
219,50,25,Master,Chennai,Finance,Startup,79.0,3,No,Female,109050.0
93,28,4,PhD,Delhi,Operations,Government,70.0,0,Yes,Female,76781.0
67,32,6,Bachelor,Chennai,Finance,Government,70.0,13,No,Male,69201.0
...,...,...,...,...,...,...,...,...,...,...,...
63,56,35,High School,Chennai,Sales,Startup,69.0,9,Yes,Male,107240.0
214,34,11,Bachelor,Pune,IT,Startup,68.0,9,Yes,Female,65050.0
146,47,26,Master,Mumbai,Finance,Private,54.0,11,Yes,Male,114628.0
103,27,5,Bachelor,Mumbai,Operations,Startup,61.0,7,Yes,Female,62627.0
181,25,4,Bachelor,Delhi,Sales,Private,60.0,9,No,Male,49037.0

In [119]:
categorical_columns

Index(['Education', 'City', 'Department', 'WorkType', 'Overtime', 'Gender'], dtype='object')

In [120]:
X_train_num = X_train.drop(columns = categorical_columns)
X_test_num = X_test.drop(columns = categorical_columns)

In [121]:
X_train_num

     Age  Experience  PerformanceScore  ProjectsCompleted    Salary
39    45          23              70.0                  3   84963.0
19    51          27              71.0                  0   87199.0
219   50          25              79.0                  3  109050.0
93    28           4              70.0                  0   76781.0
67    32           6              70.0                 13   69201.0
..   ...         ...               ...                ...       ...
63    56          35              69.0                  9  107240.0
214   34          11              68.0                  9   65050.0
146   47          26              54.0                 11  114628.0
103   27           5              61.0                  7   62627.0
181   25           4              60.0                  9   49037.0

[200 rows x 5 columns]

In [122]:
X_train_final = pd.concat([X_train_num , encoded_X_train] , axis = 1)
X_test_final = pd.concat([X_test_num , encoded_X_test] , axis = 1)

In [125]:
X_train_final

,Age,Experience,PerformanceScore,ProjectsCompleted,Salary,Education_Diploma,Education_High School,Education_Master,Education_PhD,City_Chennai,...,Department_HR,Department_IT,Department_Marketing,Department_Operations,Department_Sales,WorkType_Private,WorkType_Self-Employed,WorkType_Startup,Overtime_Yes,Gender_Male
39,45,23,70.0,3,84963.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
19,51,27,71.0,0,87199.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
219,50,25,79.0,3,109050.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
93,28,4,70.0,0,76781.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
67,32,6,70.0,13,69201.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,56,35,69.0,9,107240.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
214,34,11,68.0,9,65050.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
146,47,26,54.0,11,114628.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
103,27,5,61.0,7,62627.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
181,25,4,60.0,9,49037.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0

In [124]:
X_train_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 39 to 181
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     200 non-null    int64
 1   Experience              200 non-null    int64
 2   PerformanceScore        200 non-null    float64
 3   ProjectsCompleted       200 non-null    int64
 4   Salary                  200 non-null    float64
 5   Education_Diploma       200 non-null    float64
 6   Education_High School   200 non-null    float64
 7   Education_Master        200 non-null    float64
 8   Education_PhD           200 non-null    float64
 9   City_Chennai            200 non-null    float64
 10  City_Delhi              200 non-null    float64
 11  City_Hyderabad          200 non-null    float64
 12  City_Mumbai             200 non-null    float64
 13  City_Pune               200 non-null    float64
 14  Department_HR           200 non-null    float64
 15  Department_IT           200 non-null    float64
 16  Department_Marketing    200 non-null    float64
 17  Department_Operations   200 non-null    float64
 18  Department_Sales        200 non-null    float64
 19  WorkType_Private        200 non-null    float64
 20  WorkType_Self-Employed  200 non-null    float64
 21  WorkType_Startup        200 non-null    float64
 22  Overtime_Yes            200 non-null    float64
 23  Gender_Male             200 non-null    float64
dtypes: float64(21), int64(3)
memory usage: 39.1 KB

In [126]:
numerical_collumns = [
    'Age',
    'Experience' ,
    'PerformanceScore' ,
    'ProjectsCompleted',
    'Salary' ,

]

In [127]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_final[numerical_collumns] = scaler.fit_transform(X_train_final[numerical_collumns])
X_test_final[numerical_collumns] = scaler.transform(X_test_final[numerical_collumns])

In [128]:
X_train_final

,Age,Experience,PerformanceScore,ProjectsCompleted,Salary,Education_Diploma,Education_High School,Education_Master,Education_PhD,City_Chennai,...,Department_HR,Department_IT,Department_Marketing,Department_Operations,Department_Sales,WorkType_Private,WorkType_Self-Employed,WorkType_Startup,Overtime_Yes,Gender_Male
39,0.367364,0.512776,-0.170892,-1.004776,-0.141888,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
19,0.906285,0.878067,-0.074885,-1.665813,-0.094518,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
219,0.816464,0.695421,0.693169,-1.004776,0.368392,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
93,-1.159577,-1.222353,-0.170892,-1.665813,-0.315222,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
67,-0.800297,-1.039707,-0.170892,1.198680,-0.475803,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,1.355385,1.608647,-0.266899,0.317298,0.330047,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
214,-0.620657,-0.583095,-0.362906,0.317298,-0.563741,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
146,0.547004,0.786744,-1.707001,0.757989,0.486561,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
103,-1.249397,-1.131030,-1.034953,-0.123394,-0.615072,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
181,-1.429037,-1.222353,-1.130960,0.317298,-0.902974,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0

In [129]:
X_test_final

,Age,Experience,PerformanceScore,ProjectsCompleted,Salary,Education_Diploma,Education_High School,Education_Master,Education_PhD,City_Chennai,...,Department_HR,Department_IT,Department_Marketing,Department_Operations,Department_Sales,WorkType_Private,WorkType_Self-Employed,WorkType_Startup,Overtime_Yes,Gender_Male
177,0.906285,0.695421,-1.514987,1.639371,0.230118,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
211,-0.710477,-0.583095,1.845250,0.537643,-0.339712,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
246,-0.351196,-0.126482,-0.938946,1.198680,-0.490653,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
166,-0.261376,-0.400449,0.885183,0.757989,-0.094518,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
193,0.996105,0.786744,-1.130960,0.757989,0.110953,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70,0.996105,1.243357,1.077196,1.639371,-0.094518,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
233,-0.441017,-0.674417,-1.803007,0.096952,-0.111233,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
188,0.367364,0.421454,0.597162,1.639371,0.521007,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
164,-0.800297,-0.948385,-1.034953,0.096952,-0.711463,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
56,-0.441017,-0.583095,-1.707001,0.537643,-0.669093,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
210,0.996105,1.152034,-0.650926,0.757989,0.292041,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
167,-1.339217,-1.404998,-0.746933,-0.343739,-0.988158,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
218,1.535025,1.699970,0.885183,-1.225121,0.558292,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
207,-1.788318,-1.587643,0.309142,-0.784430,-0.269865,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
50,-0.441017,-0.400449,0.405149,-1.445467,-0.841432,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
100,1.355385,1.517325,-1.899014,0.978334,1.012220,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
206,-1.339217,-1.313675,0.597162,-0.784430,-0.602531,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
95,1.265565,1.426002,-0.842940,-0.784430,0.180821,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
20,1.355385,1.334679,0.021121,-1.445467,0.139447,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
14,0.726644,0.878067,-0.746933,-0.123394,-0.252769,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
223,0.816464,0.604099,-2.091028,0.978334,-0.064838,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
21,1.085925,0.969389,0.405149,-0.564085,0.924642,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
249,-0.800297,-1.039707,2.613305,-0.564085,-0.960173,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
54,-0.620657,-0.583095,-1.322974,-0.343739,-0.464872,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
228,1.445205,1.608647,0.117128,1.419026,0.654726,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
78,0.457184,0.512776,1.557230,1.639371,0.204040,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
143,0.726644,0.512776,-0.074885,0.757989,-0.170169,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
74,-1.788318,-1.587643,0.789176,1.639371,-0.859587,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
238,-0.351196,-0.583095,-0.842940,-0.123394,3.869355,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
38,-0.530837,-0.400449,1.557230,-1.225121,-0.038082,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65,-0.081736,-0.217804,0.597162,1.419026,-0.168220,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
117,-1.339217,-1.496320,1.173203,1.419026,-0.094518,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
198,1.265565,1.517325,-0.938946,1.198680,0.569775,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
60,-1.518857,-1.587643,-1.514987,-1.445467,-1.207908,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
1,-0.530837,-0.309127,-1.707001,-0.123394,-0.577257,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
110,1.265565,1.152034,2.037264,-1.445467,0.648349,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
77,0.816464,0.969389,0.021121,-1.225121,-0.139134,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
133,1.265565,1.060712,0.309142,1.639371,0.152666,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0
173,0.816464,0.604099,-0.458912,0.317298,0.216645,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
116,-0.081736,-0.217804,-0.458912,-1.445467,-0.316641,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
144,-0.800297,-0.948385,0.213135,1.639371,-0.002258,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
242,-0.979937,-1.131030,0.405149,-1.004776,-0.063355,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
96,-1.698498,-1.496320,-1.899014,1.639371,-0.945767,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
187,1.175745,1.243357,2.517298,1.198680,0.390318,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
126,0.906285,0.786744,-0.458912,0.096952,0.624410,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
52,1.175745,1.243357,-2.091028,0.096952,1.037599,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
113,-0.081736,0.056163,1.173203,-1.004776,0.064474,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
59,-1.069757,-1.131030,0.693169,1.639371,-0.561326,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
107,-1.518857,-1.496320,1.269210,1.639371,-0.794635,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
234,-1.339217,-1.587643,-1.322974,-1.665813,-1.163526,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [130]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(X_train_final , y_train)

LogisticRegression()

In [132]:
y_pred = lr.predict(X_test_final)

In [134]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

print("confusion matrix :- " , confusion_matrix(y_test , y_pred))
print("classification report :- " , classification_report(y_test , y_pred))
accuracy = accuracy_score(y_test , y_pred)
print("accuracy score :- " , accuracy)

confusion matrix :-  [[44  1]
 [ 2  3]]
classification report :-                precision    recall  f1-score   support

          No       0.96      0.98      0.97        45
         Yes       0.75      0.60      0.67         5

    accuracy                           0.94        50
   macro avg       0.85      0.79      0.82        50
weighted avg       0.94      0.94      0.94        50

accuracy score :-  0.94

In [138]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state = 42)

In [139]:
dt.fit(X_train_final , y_train)

DecisionTreeClassifier(random_state=42)

In [141]:
y_pred_dt = dt.predict(X_test_final)

In [143]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
print("Accuracy score :- " , accuracy_score(y_test , y_pred_dt))
print("Confusion matrix :- " , confusion_matrix(y_test , y_pred_dt))
print("Classification report :- " , classification_report(y_test , y_pred_dt))

Accuracy score :-  1.0
Confusion matrix :-  [[45  0]
 [ 0  5]]
Classification report :-                precision    recall  f1-score   support

          No       1.00      1.00      1.00        45
         Yes       1.00      1.00      1.00         5

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

In [145]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state = 42)

In [146]:
rf.fit(X_train_final , y_train)

RandomForestClassifier(random_state=42)

In [147]:
y_pred_rf = rf.predict(X_test_final)

In [148]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
print("Accuracy score :- " , accuracy_score(y_test , y_pred_rf))
print("Confusion matrix :- " , confusion_matrix(y_test , y_pred_rf))
print("Classification report :- " , classification_report(y_test , y_pred_rf))

Accuracy score :-  0.98
Confusion matrix :-  [[45  0]
 [ 1  4]]
Classification report :-                precision    recall  f1-score   support

          No       0.98      1.00      0.99        45
         Yes       1.00      0.80      0.89         5

    accuracy                           0.98        50
   macro avg       0.99      0.90      0.94        50
weighted avg       0.98      0.98      0.98        50

In [158]:
from xgboost import XGBClassifier

xgb = XGBClassifier(random_state = 42, eval_metric = 'logloss')

In [159]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

In [160]:
xgb.fit(X_train_final , y_train_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [161]:
y_pred_xgb = xgb.predict(X_test_final)

In [163]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
print("Accuracy score :- " , accuracy_score(y_test_encoded , y_pred_xgb))
print("Confusion matrix :- " , confusion_matrix(y_test_encoded , y_pred_xgb))
print("Classification report :- " , classification_report(y_test_encoded , y_pred_xgb))

Accuracy score :-  1.0
Confusion matrix :-  [[45  0]
 [ 0  5]]
Classification report :-                precision    recall  f1-score   support

           0       1.00      1.00      1.00        45
           1       1.00      1.00      1.00         5

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

In [165]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
print("Accuracy score Logistic Regression :- " , accuracy_score(y_test , y_pred))
print("Accuracy score Decision Tree :- " , accuracy_score(y_test , y_pred_dt))
print("Accuracy score Random Forest :- " , accuracy_score(y_test , y_pred_rf))
print("Accuracy score XGBoost:- " , accuracy_score(y_test_encoded , y_pred_xgb))

Accuracy score Logistic Regression :-  0.94
Accuracy score Decision Tree :-  1.0
Accuracy score Random Forest :-  0.98
Accuracy score XGBoost:-  1.0

In [168]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [169]:
X_train_final.shape

(200, 24)

In [175]:
model = Sequential()

model.add(Dense(32 , activation = 'relu' , input_dim = 24))
model.add(Dense(16, activation = 'relu'))
model.add(Dense(1 , activation = 'sigmoid'))

In [176]:
model.compile(optimizer = 'adam' , loss = 'binary_crossentropy' ,  metrics = ['accuracy'])

In [177]:
history = model.fit(X_train_final , y_train_encoded , epochs = 100 , batch_size = 16 , validation_split = 0.2 , verbose = 1)

Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.3812 - loss: 0.8122 - val_accuracy: 0.5000 - val_loss: 0.6925
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6375 - loss: 0.6666 - val_accuracy: 0.8000 - val_loss: 0.5893
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8188 - loss: 0.5591 - val_accuracy: 0.9000 - val_loss: 0.5187
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9000 - loss: 0.4779 - val_accuracy: 0.8750 - val_loss: 0.4638
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9250 - loss: 0.4111 - val_accuracy: 0.8500 - val_loss: 0.4199
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9250 - loss: 0.3591 - val_accuracy: 0.8500 - val_loss: 0.3844
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9187 - loss: 0.3130 - val_accuracy: 0.8500 - val_loss: 0.3587
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9187 - loss: 0.2788 - val_accuracy: 0.8500 - val_loss: 0.3432
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9187 - loss: 0.2494 - val_accuracy: 0.8500 - val_loss: 0.3326
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9187 - loss: 0.2282 - val_accuracy: 0.8500 - val_loss: 0.3252
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9187 - loss: 0.2128 - val_accuracy: 0.8500 - val_loss: 0.3223
Epoch 12/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9250 - loss: 0.1986 - val_accuracy: 0.8500 - val_loss: 0.3158
Epoch 13/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9250 - loss: 0.1872 - val_accuracy: 0.8500 - val_loss: 0.3129
Epoch 14/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9250 - loss: 0.1773 - val_accuracy: 0.8500 - val_loss: 0.3100
Epoch 15/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9250 - loss: 0.1682 - val_accuracy: 0.8500 - val_loss: 0.3033
Epoch 16/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9250 - loss: 0.1588 - val_accuracy: 0.8500 - val_loss: 0.3002
Epoch 17/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9250 - loss: 0.1511 - val_accuracy: 0.8500 - val_loss: 0.2997
Epoch 18/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9250 - loss: 0.1429 - val_accuracy: 0.8500 - val_loss: 0.2969
Epoch 19/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9250 - loss: 0.1353 - val_accuracy: 0.8500 - val_loss: 0.2961
Epoch 20/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9250 - loss: 0.1276 - val_accuracy: 0.8500 - val_loss: 0.2925
Epoch 21/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9312 - loss: 0.1215 - val_accuracy: 0.8500 - val_loss: 0.2890
Epoch 22/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9375 - loss: 0.1147 - val_accuracy: 0.8500 - val_loss: 0.2873
Epoch 23/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9375 - loss: 0.1084 - val_accuracy: 0.8500 - val_loss: 0.2871
Epoch 24/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9500 - loss: 0.1022 - val_accuracy: 0.8500 - val_loss: 0.2919
Epoch 25/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9625 - loss: 0.0972 - val_accuracy: 0.8750 - val_loss: 0.2918
Epoch 26/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9688 - loss: 0.0915 - val_accuracy: 0.8750 - val_loss: 0.2952
Epoch 27/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9688 - loss: 0.0865 - val_accuracy: 0.8500 - val_loss: 0.2980
Epoch 28/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9812 - loss: 0.0817 - val_accuracy: 0.8500 - val_loss: 0.2993
Epoch 29/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9812 - loss: 0.0775 - val_accuracy: 0.8750 - val_loss: 0.3011
Epoch 30/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9750 - loss: 0.0729 - val_accuracy: 0.8750 - val_loss: 0.3063
Epoch 31/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9750 - loss: 0.0692 - val_accuracy: 0.8750 - val_loss: 0.3124
Epoch 32/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9750 - loss: 0.0653 - val_accuracy: 0.8500 - val_loss: 0.3130
Epoch 33/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9750 - loss: 0.0616 - val_accuracy: 0.8500 - val_loss: 0.3191
Epoch 34/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9812 - loss: 0.0582 - val_accuracy: 0.8500 - val_loss: 0.3272
Epoch 35/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9812 - loss: 0.0553 - val_accuracy: 0.8500 - val_loss: 0.3302
Epoch 36/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9875 - loss: 0.0522 - val_accuracy: 0.8500 - val_loss: 0.3340
Epoch 37/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9875 - loss: 0.0504 - val_accuracy: 0.8500 - val_loss: 0.3390
Epoch 38/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9875 - loss: 0.0469 - val_accuracy: 0.8500 - val_loss: 0.3457
Epoch 39/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9875 - loss: 0.0453 - val_accuracy: 0.8500 - val_loss: 0.3454
Epoch 40/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9875 - loss: 0.0429 - val_accuracy: 0.8500 - val_loss: 0.3535
Epoch 41/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9875 - loss: 0.0406 - val_accuracy: 0.8500 - val_loss: 0.3596
Epoch 42/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9875 - loss: 0.0388 - val_accuracy: 0.8500 - val_loss: 0.3631
Epoch 43/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9875 - loss: 0.0371 - val_accuracy: 0.8500 - val_loss: 0.3719
Epoch 44/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9875 - loss: 0.0357 - val_accuracy: 0.8500 - val_loss: 0.3755
Epoch 45/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9875 - loss: 0.0334 - val_accuracy: 0.8500 - val_loss: 0.3837
Epoch 46/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9875 - loss: 0.0319 - val_accuracy: 0.8500 - val_loss: 0.3856
Epoch 47/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9875 - loss: 0.0306 - val_accuracy: 0.8500 - val_loss: 0.3914
Epoch 48/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9937 - loss: 0.0289 - val_accuracy: 0.8500 - val_loss: 0.3963
Epoch 49/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9937 - loss: 0.0277 - val_accuracy: 0.8500 - val_loss: 0.4017
Epoch 50/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9937 - loss: 0.0262 - val_accuracy: 0.8500 - val_loss: 0.4081
Epoch 51/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9937 - loss: 0.0248 - val_accuracy: 0.8500 - val_loss: 0.4135
Epoch 52/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0236 - val_accuracy: 0.8500 - val_loss: 0.4185
Epoch 53/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0225 - val_accuracy: 0.8500 - val_loss: 0.4251
Epoch 54/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0214 - val_accuracy: 0.8500 - val_loss: 0.4280
Epoch 55/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.0206 - val_accuracy: 0.8500 - val_loss: 0.4398
Epoch 56/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0202 - val_accuracy: 0.8500 - val_loss: 0.4413
Epoch 57/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0186 - val_accuracy: 0.8500 - val_loss: 0.4483
Epoch 58/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0178 - val_accuracy: 0.8500 - val_loss: 0.4553
Epoch 59/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0168 - val_accuracy: 0.8500 - val_loss: 0.4591
Epoch 60/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0163 - val_accuracy: 0.8500 - val_loss: 0.4624
Epoch 61/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0155 - val_accuracy: 0.8500 - val_loss: 0.4687
Epoch 62/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0147 - val_accuracy: 0.8500 - val_loss: 0.4744
Epoch 63/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0141 - val_accuracy: 0.8750 - val_loss: 0.4786
Epoch 64/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0134 - val_accuracy: 0.8750 - val_loss: 0.4843
Epoch 65/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0128 - val_accuracy: 0.8750 - val_loss: 0.4900
Epoch 66/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0122 - val_accuracy: 0.8750 - val_loss: 0.4938
Epoch 67/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0117 - val_accuracy: 0.8750 - val_loss: 0.4989
Epoch 68/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0113 - val_accuracy: 0.8750 - val_loss: 0.5046
Epoch 69/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0106 - val_accuracy: 0.8750 - val_loss: 0.5088
Epoch 70/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0103 - val_accuracy: 0.8750 - val_loss: 0.5128
Epoch 71/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0098 - val_accuracy: 0.8750 - val_loss: 0.5178
Epoch 72/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0094 - val_accuracy: 0.8750 - val_loss: 0.5222
Epoch 73/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0090 - val_accuracy: 0.8750 - val_loss: 0.5271
Epoch 74/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0086 - val_accuracy: 0.8750 - val_loss: 0.5325
Epoch 75/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0082 - val_accuracy: 0.8750 - val_loss: 0.5363
Epoch 76/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0080 - val_accuracy: 0.8750 - val_loss: 0.5430
Epoch 77/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0076 - val_accuracy: 0.8750 - val_loss: 0.5443
Epoch 78/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0073 - val_accuracy: 0.8750 - val_loss: 0.5475
Epoch 79/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0071 - val_accuracy: 0.8750 - val_loss: 0.5533
Epoch 80/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0067 - val_accuracy: 0.8750 - val_loss: 0.5566
Epoch 81/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0065 - val_accuracy: 0.8750 - val_loss: 0.5605
Epoch 82/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0063 - val_accuracy: 0.8750 - val_loss: 0.5651
Epoch 83/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0060 - val_accuracy: 0.8750 - val_loss: 0.5690
Epoch 84/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0058 - val_accuracy: 0.8750 - val_loss: 0.5729
Epoch 85/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.8750 - val_loss: 0.5762
Epoch 86/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.8750 - val_loss: 0.5801
Epoch 87/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0052 - val_accuracy: 0.8750 - val_loss: 0.5841
Epoch 88/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0050 - val_accuracy: 0.8750 - val_loss: 0.5885
Epoch 89/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0048 - val_accuracy: 0.8750 - val_loss: 0.5899
Epoch 90/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0047 - val_accuracy: 0.8750 - val_loss: 0.5944
Epoch 91/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0045 - val_accuracy: 0.8750 - val_loss: 0.5986
Epoch 92/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0044 - val_accuracy: 0.8750 - val_loss: 0.6027
Epoch 93/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0042 - val_accuracy: 0.8750 - val_loss: 0.6045
Epoch 94/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0041 - val_accuracy: 0.8750 - val_loss: 0.6086
Epoch 95/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0040 - val_accuracy: 0.8750 - val_loss: 0.6118
Epoch 96/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0038 - val_accuracy: 0.8750 - val_loss: 0.6173
Epoch 97/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0037 - val_accuracy: 0.8750 - val_loss: 0.6193
Epoch 98/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0036 - val_accuracy: 0.8750 - val_loss: 0.6222
Epoch 99/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.8750 - val_loss: 0.6255
Epoch 100/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0034 - val_accuracy: 0.8750 - val_loss: 0.6286

In [178]:
y_pred_Neural_network = model.predict(X_test_final)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

In [179]:
y_pred_Neural_network.shape

(50, 1)

In [192]:
y_pred_Neural_network_new = (y_pred_Neural_network > 0.5).astype(int)

In [193]:
y_pred_Neural_network_new = y_pred_Neural_network_new.flatten()

In [194]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
print("Accuracy score :- " , accuracy_score(y_test_encoded , y_pred_Neural_network_new))
print("Confusion matrix :- " , confusion_matrix(y_test_encoded , y_pred_Neural_network_new))
print("Classification report :- " , classification_report(y_test_encoded , y_pred_Neural_network_new))

Accuracy score :-  0.94
Confusion matrix :-  [[44  1]
 [ 2  3]]
Classification report :-                precision    recall  f1-score   support

           0       0.96      0.98      0.97        45
           1       0.75      0.60      0.67         5

    accuracy                           0.94        50
   macro avg       0.85      0.79      0.82        50
weighted avg       0.94      0.94      0.94        50

In [195]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
print("Accuracy score Logistic Regression :- " , accuracy_score(y_test , y_pred))
print("Accuracy score Decision Tree :- " , accuracy_score(y_test , y_pred_dt))
print("Accuracy score Random Forest :- " , accuracy_score(y_test , y_pred_rf))
print("Accuracy score XGBoost:- " , accuracy_score(y_test_encoded , y_pred_xgb))
print("Accuracy score Neural Network :- " , accuracy_score(y_test_encoded , y_pred_Neural_network_new))

Accuracy score Logistic Regression :-  0.94
Accuracy score Decision Tree :-  1.0
Accuracy score Random Forest :-  0.98
Accuracy score XGBoost:-  1.0
Accuracy score Neural Network :-  0.94